### ISSUE TITLE
Menu Links Key Error

### ISSUE THREAD

**Issue by Qurus** [prismicio-community/nextjs-starter-prismic-multi-language#7]
This example has this error. 
`Warning: Encountered two children with the same key, `Xs5rBhEAACEAIueu`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in MenuLinks (at Navigation.js:23)
    in Navigation (at Header.js:17)
    in ul (at Header.js:16)
    in div (at Header.js:15)
    in header (at Header.js:7)
    in Header (at Layout.js:26)
    in Layout (at pages/index.js:19)
    in Homepage (at _app.js:4)
    in MyApp
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in Root`

**Comment by angeloashmore** [comment]
Hey @Qurus, the starter has been updated with a refreshed design and new codebase. The error you posted shouldn't happen anymore.

If you do see it happen again, please open a new issue or comment here and I can take a look. Thanks!
